# markdown 
markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: "2,3"

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "NZGOAL Software Extension (Revision May 2016)"
description: "Transperant revision of NZGOAL-SE"
#baseurl: https://sourcecode.cio.gov
# Uncomment the following line for localhost development at http://127.0.0.1:4000/nzgoal
baseurl: /nzgoal-se/

# GitHub information
org_name: opendatanz
repo_name: nzgoal-se
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: About the revision process
  url: /nzgoal-se/
- text: Introduction
  url: /nzgoal-se/introduction/
- text: Legal and policy context
  url: /nzgoal-se/legal-and-policy-context/
- text: Policy principles
  url: /nzgoal-se/policy-principles/
- text: Review and release process
  url: /nzgoal-se/review-and-release-process/

# sass
sass:
  sass_dir: _sass
